### ISSUE TITLE
GH Action fails to get requirements to build wheel

### ISSUE THREAD

**Issue by dkamenov-fitted** [bewuethr/yamllint-action#14]
Looks like this github action is broken for a lot of users right now due to the following error:
```
#5 2.674 Collecting yamllint==1.28.0
#5 2.786   Downloading yamllint-1.28.0-py2.py3-none-any.whl (62 kB)
#5 2.808      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/62.4 kB 2.8 MB/s eta 0:00:00
#5 2.845 Collecting pathspec>=0.5.3
#5 2.865   Downloading pathspec-0.11.1-py3-none-any.whl (29 kB)
#5 2.925 Collecting pyyaml
#5 2.945   Downloading PyYAML-6.0.tar.gz (124 kB)
#5 2.972      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 5.3 MB/s eta 0:00:00
#5 3.142   Installing build dependencies: started
#5 8.728   Installing build dependencies: finished with status 'done'
#5 8.729   Getting requirements to build wheel: started
#5 9.025   Getting requirements to build wheel: finished with status 'error'
#5 9.031   error: subprocess-exited-with-error
#5 9.031
#5 9.031   × Getting requirements to build wheel did not run successfully.
#5 9.031   │ exit code: 1
#5 9.031   ╰─> [54 lines of output]
#5 9.031       running egg_info
#5 9.031       writing lib/PyYAML.egg-info/PKG-INFO
#5 9.031       writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
#5 9.031       writing top-level names to lib/PyYAML.egg-info/top_level.txt
#5 9.031       Traceback (most recent call last):
#5 9.031         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
#5 9.031           main()
#5 9.031         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
#5 9.031           json_out['return_val'] = hook(**hook_input['kwargs'])
#5 9.031                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#5 9.031         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#5 9.031           return hook(config_settings)
#5 9.031                  ^^^^^^^^^^^^^^^^^^^^^
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
#5 9.031           return self._get_build_requires(config_settings, requirements=['wheel'])
#5 9.031                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
#5 9.031           self.run_setup()
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
#5 9.031           exec(code, locals())
#5 9.031         File "<string>", line 288, in <module>
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
#5 9.031           return distutils.core.setup(**attrs)
#5 9.031                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
#5 9.031           return run_commands(dist)
#5 9.031                  ^^^^^^^^^^^^^^^^^^
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#5 9.031           dist.run_commands()
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#5 9.031           self.run_command(cmd)
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
#5 9.031           super().run_command(command)
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#5 9.031           cmd_obj.run()
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
#5 9.031           self.find_sources()
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
#5 9.031           mm.run()
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
#5 9.031           self.add_defaults()
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
#5 9.031           sdist.add_defaults(self)
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
#5 9.031           super().add_defaults()
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
#5 9.031           self._add_defaults_ext()
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
#5 9.031           self.filelist.extend(build_ext.get_source_files())
#5 9.031                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#5 9.031         File "<string>", line 204, in get_source_files
#5 9.031         File "/tmp/pip-build-env-ty_s2l2u/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
#5 9.031           raise AttributeError(attr)
#5 9.031       AttributeError: cython_sources
#5 9.031       [end of output]
#5 9.031
#5 9.031   note: This error originates from a subprocess, and is likely not a problem with pip.
#5 9.033 error: subprocess-exited-with-error
#5 9.033
#5 9.033 × Getting requirements to build wheel did not run successfully.
#5 9.033 │ exit code: 1
#5 9.033 ╰─> See above for output.
#5 9.033
#5 9.033 note: This error originates from a subprocess, and is likely not a problem with pip.
#5 9.172
#5 9.172 [notice] A new release of pip available: 22.3 -> 23.2
#5 9.172 [notice] To update, run: pip install --upgrade pip
```
This might be related to the following:
 https://github.com/yaml/pyyaml/issues/724

**Comment by bewuethr** [comment]
Thank you for reporting! It looks like there was a fix in PyYAML (yaml/pyyaml#702) that pins Cython to a version older than 3.0, and the fix was released in [version 6.0.1](https://github.com/yaml/pyyaml/releases/tag/6.0.1). This also prevents the error you're seeing with the yamllint action, as far as I can tell.
